### ISSUE TITLE
 ERROR in app: Exception on / [GET]

### ISSUE THREAD

**Issue by Flight1903** [richgieg/runo#4]
C:\games\runo>flask run
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2018-06-28 01:36:54,869] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\games\games_test\venv\runo\app.py", line 14, in index
    open_games = get_open_games()
  File "C:\games\games_test\venv\runo\runo.py", line 93, in get_open_games
    do_house_keeping()
  File "C:\games\games_test\venv\runo\runo.py", line 88, in do_house_keeping
    for game in get_old_games():
  File "C:\games\games_test\venv\runo\runo.py", line 77, in get_old_games
    game_files = os.listdir(GAME_FILE_PATH)
WindowsError: [Error 3] The system cannot find the path specified: 'games\\*.*'
127.0.0.1 - - [28/Jun/2018 01:36:54] "GET / HTTP/1.1" 500 -

**Comment by Flight1903** [comment]
works - you probably want to put an empty games folder in the repo, but this works great

**Comment by richgieg** [comment]
Nice, glad it worked for you! I think I tried that before but I believe git
repos don't allow empty directories. Either way, I think the app should be
responsible for creating it. It's an oversight on my part. Anyway, thanks
for reporting it!

**Comment by richgieg** [comment]
App uses Google Firestore now. Collection "games" does not need to exist. It will be created automatically the first time a game is written.
